import pandas as pd
import math

print('This program tests Data csv sheets generated by DataAnalysis.py.')
print('Please link the csv file with full path: ', end='')

dataSheet = input()

if dataSheet[len(dataSheet)-7:len(dataSheet)-4] == 'SMA':
    print('\nThis is a test of the 3 layer rolling SMA algo.')
    print('The program starts with 100$ and invests it according to the algorithm (once at least all the SMAs have time to be generated)')
    dataParsed = pd.read_csv(dataSheet, index_col='Date')
    lastPrice = 0.0
    USD = 100.0
    Crypto = 0.0
    dayNum = 1
    tradeDates = ['']*0
    print('\nStarting simulation of bot from ' + dataParsed.index[0] + ' to ' + dataParsed.index[len(dataParsed)-1])
    for day in dataParsed.index:
        print('\nDay: ' + str(dayNum) + ' (' + day + ')')
        SMA1 = dataParsed.loc[day, dataParsed.columns[1]]
        SMA2 = dataParsed.loc[day, dataParsed.columns[2]]
        SMA3 = dataParsed.loc[day, dataParsed.columns[3]]
        lastPrice = dataParsed.loc[day, dataParsed.columns[0]]

        if math.isnan(SMA1) or math.isnan(SMA2) or math.isnan(SMA3):
            print('Not enough data to trade')
        else:
            if SMA1 > SMA2 and SMA1 > SMA3 and USD > 0.0:
                print('Buying Crypto/Stock at price of: $' + str(dataParsed.loc[day, dataParsed.columns[0]]))
                Crypto = USD/lastPrice
                USD = 0.0
                tradeDates.append(day)
            elif SMA1 < SMA2 or SMA1 < SMA3:
                if Crypto > 0.0:
                    print('Selling Crypto/Stock at price of: $' + str(dataParsed.loc[day, dataParsed.columns[0]]))
                    USD = lastPrice*Crypto
                    Crypto = 0.0
                    tradeDates.append(day)
                else:
                    print('Holdings optimal, no buying or selling.')
            else:
                print('Holdings optimal, no buying or selling.')

        print('Price: $' + str(lastPrice))
        print('USD holdings: ' + str(USD))
        print('Crypto/Stock holdings: ' + str(Crypto))
        dayNum = dayNum + 1

    print('\nDone!')
    print('Bot placed trades on these days:')
    print(tradeDates)
    if USD > 0.0:
        print('Final value of portfolio increased by ' + str(round(USD)) + '%')
    else:
        print('Final value of portfolio increased by ' + str(round(lastPrice*Crypto)) + '%')